### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by mdavidsaver**
Updates based on some practice installs.

### CODE REVIEW

**Comment by mdavidsaver** [comment]
@shroffk I know at one point I had some `curl` incantations to add/remove a CF tag through the service as a test of the elasticsearch install, but I can't find them now.  Do you remember how to do this?

**Comment by mdavidsaver** [comment]
Also, rather than filling up the README with distribution/container/... specific instructions, I'll be adding wiki pages https://github.com/ChannelFinder/ChannelFinder-SpringBoot/wiki

**Comment by mdavidsaver** [comment]
@shroffk What is going on with `src/main/resources/keystore/newcf.p12`?  It looks like this is being referenced by the default `application.properties`.  Is this being used somehow?

```
$ keytool -keystore src/main/resources/keystore/newcf.p12 -list
...
Your keystore contains 1 entry

cf, Jul 30, 2019, PrivateKeyEntry,
```

**Comment by mdavidsaver** [comment]
I guess `newcf.p12` is an unused "dummy" key?

fyi. One way to create a truly empty keystore file (only 88 bytes) is:

```sh
keytool -keystore cf.keystore -storepass password -genkeypair -alias unused -dname "CN=unused"
keytool -keystore cf.keystore -storepass password -delete -alias unused
```

**Comment by mdavidsaver** [comment]
API document needs to mention ".../resources/..." and give at least one example of a full URL.

```sh
$ curl http://localhost:8080/ChannelFinder/resources/tags
[]
```

**Review by shroffk — APPROVED** [review]

**Comment by shroffk** [comment]
> API document needs to mention ".../resources/..." and give at least one example of a full URL.
> 
> ```shell
> $ curl http://localhost:8080/ChannelFinder/resources/tags
> []
> ```

I fixed this with a "example" at the start of the individual URL calls.

**Comment by shroffk** [comment]
https://channelfinder.readthedocs.io/en/latest/api.html#web-service-urls-and-operations

I hope it makes sense...

**Comment by shroffk** [comment]
Also, Thanks for adding the verification section... I should have documented it when I added it.
It is very useful to checking the state of the services and if it has a connection with elastic and the versions match etc...

**Pull request merged**
