### PR TITLE
Elastic8

### PR DESCRIPTION
**Pull request by shroffk**
Preparing for elastic 8

### CODE REVIEW

**Comment by shroffk** [comment]
@tynanford @fredrik-soderberg I am ready to merge this

**Review by georgweiss — COMMENTED** [review]
Sorry, cannot add any review at this point as I am ooo.

**Review by tynanford — APPROVED** [review]
Nice work @shroffk !

Took a bit to figure out how to get elastic 8 configured but after that CF started up and worked. My first test was with me manually populating ES with es8_mapping_definitions.sh . CF didn't seem to do that for me though when I tested with a blank ES instance. Isn't that supposed to be automatic now?

**Comment by shroffk** [comment]
Yes it should be automatically creating the indices.
Let me double check

**Comment by shroffk** [comment]
@tynanford 
I just pushed a commit which should generate the required indices

**Comment by tynanford** [comment]
that fixed it thanks. Last thing, I see version 4.0.0 still in most places but also 4.0.5 in pom.xml

```
$ curl localhost:8080/ChannelFinder
{
    "name": "ChannelFinder Service",
    "version": "4.0.0",
    "elastic": {
....
```

https://github.com/ChannelFinder/ChannelFinderService/blob/elastic8/src/main/java/org/phoebus/channelfinder/InfoManager.java#L32

**Comment by shroffk** [comment]
ya...
After this merge I want to sync up the next release version with the rest of the new epics services... so 4.7.0
I am hoping to fix all that as part of the next release

**Comment by tynanford** [comment]
got it, thanks!

**Review by fredrik-soderberg — APPROVED** [review]
I have reviewed the code and also performed some basic testing with es8. The only issue that I have found is related to the docker files that needs to be updated. As we talked about earlier it might be best to fix the docker files after this merge.

**Pull request merged**
